##############
### local
##############

server:
  port: 8088

spring:
  datasource:    
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: oscer
    password: Oscer2022@!
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:    
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
        ddl-auto: none  



logging:
  config: classpath:log4j2.xml


